"""Pydantic contract between the Next.js BFF and this service.

Why this exists: this is the one file the BFF's TypeScript client
(frontend/src/lib/ai-service-client.ts) and every ModelProvider
implementation must agree on. Field names mirror the Prisma `Brief`/
`Variant` models 1:1 (snake_case here, camelCase there — converted at the
BFF boundary) so nothing needs remapping beyond that.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class BriefInput(BaseModel):
    genres: list[str]
    audience: str
    budget_tier: str
    runtime_minutes: int
    region: str
    language: str
    censorship_framework: str
    censorship_rating: str
    location_type: str
    cast_size: str
    vfx_dependency: str
    freeform_notes: str | None = None


class MainCharacter(BaseModel):
    name: str
    age: str
    motivation: str
    internal_conflict: str
    external_conflict: str
    arc: str


class ActOne(BaseModel):
    opening_image: str
    inciting_incident: str
    first_turning_point: str


class ActTwo(BaseModel):
    rising_conflict: str
    midpoint: str
    complications: str
    lowest_point: str


class ActThree(BaseModel):
    climax: str
    resolution: str
    final_image: str


class ThreeActStructure(BaseModel):
    act1: ActOne
    act2: ActTwo
    act3: ActThree


class ProductionConsiderations(BaseModel):
    locations: str
    vfx: str
    cast: str
    production_scale: str


class VariantOutput(BaseModel):
    working_title: str
    genre: str
    tone: str
    target_audience: str
    logline: str
    high_concept: str
    theme: str
    emotional_core: str
    world_building: str
    main_characters: list[MainCharacter]
    three_act_structure: ThreeActStructure
    major_plot_twists: list[str]
    character_relationships: list[str]
    visual_style: str
    cinematic_references: list[str]
    production_considerations: ProductionConsiderations
    constraint_validation: dict[str, str]
    uniqueness_note: str
    central_conflict: str
    production_complexity: Literal["low", "medium", "high"]
    estimated_locations: int
    estimated_principal_cast: int
    vfx_level_used: str
    # Populated only by the on-demand /internal/screenplay action, never by
    # generate/refine — a variant is a development document first; the
    # formatted script excerpt is a separate, explicitly-requested step.
    screenplay_excerpt: str | None = None


class GenerateRequest(BaseModel):
    brief: BriefInput
    # 3-5 per the ideation spec ("generate 3-5 variants, every one
    # fundamentally different"); each variant is now a full development
    # document generated by its own concurrent model call (see
    # openai_compatible.py), so this is no longer "how many items in one
    # JSON array" but "how many concurrent generation calls."
    variant_count: int = Field(default=3, ge=1, le=5)
    # Per-request override of the server's MODEL_PROVIDER default — the
    # NVIDIA/Groq sidebar toggle (design.md Entry 19). None = use whatever
    # MODEL_PROVIDER is configured in ai-service/.env (unchanged behavior
    # for callers that predate the toggle, e.g. the eval harness).
    provider: Literal["mock", "nim", "groq"] | None = None


class GenerateResponse(BaseModel):
    variants: list[VariantOutput]
    model: str
    provider: str


class RefineRequest(BaseModel):
    brief: BriefInput
    variant: VariantOutput
    instruction: str
    provider: Literal["mock", "nim", "groq"] | None = None


class RefineResponse(BaseModel):
    variant: VariantOutput
    model: str
    provider: str


class ScreenplayRequest(BaseModel):
    brief: BriefInput
    variant: VariantOutput
    scene_target: int = Field(default=4, ge=2, le=10)
    provider: Literal["mock", "nim", "groq"] | None = None


class ScreenplayResponse(BaseModel):
    screenplay_excerpt: str
    model: str
    provider: str


class ValidateRequest(BaseModel):
    brief: BriefInput
    variant: VariantOutput


class ValidateResponse(BaseModel):
    scores: dict[str, int]
    mean_adherence: float
    notes: str = ""
